# Visa Bulletin PDF Parsing

This notebook extracts Family-Sponsored Visa Bulletin data from the official PDF files.

The PDFs are divided into two formats:

- Old format: October 2016 – October 2025
- New format: November 2025 – September 2026

Each bulletin contains two tables:
1. Final Action Dates
2. Dates for Filing

For each table, I collect the five family-sponsored categories (F1, F2A, F2B, F3, F4) across five chargeability areas.

In [23]:
import re # Regular expressions are used to validate cutoff date values.
import calendar # Calendar is used to convert month names from filenames into month numbers.
from pathlib import Path # Path makes it easier to work with folders and file locations.

import pandas as pd 
# Pandas is used to create and manage the final dataset.
import pdfplumber # pdfplumber is used to extract text and tables from the Visa Bulletin PDFs.

In [24]:
PROJECT_ROOT = Path.cwd() # Find the main project folder.

# If the notebook is running from the notebooks folder, 
# move one level up to the main project folder.
if PROJECT_ROOT.name == "notebooks": 
    PROJECT_ROOT = PROJECT_ROOT.parent

RAW_DIR = PROJECT_ROOT / "data" / "raw_pdfs" # Folder containing the original downloaded PDFs.
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" # Folder where the cleaned/processed data will eventually be saved.

#Quick check to make sure Python can find all 120 PDFs.
print("Raw PDF folder:", RAW_DIR) 
print("PDF count:", len(list(RAW_DIR.rglob("*.pdf"))))

Raw PDF folder: /Users/serratak/Desktop/visa-bulletin-project/visa-bulletin-project/data/raw_pdfs
PDF count: 120

In [25]:
# The five chargeability areas shown in each Family-Sponsored table.
# Their order matters because it matches the order of the PDF columns.
AREAS = [
    "All Chargeability Areas Except Those Listed",
    "China",
    "India",
    "Mexico",
    "Philippines"
]

# A valid cutoff value can be:
# - A date in DDMMMYY format, such as 22SEP09
# - C = Current
# - U = Unavailable
DATE_PATTERN = re.compile(
    r"^(?:\d{2}[A-Z]{3}\d{2}|C|U)$"
)

In [ ]:
# Create a dictionary that converts month names into month numbers.
# Example: "october" -> 10
MONTHS = {
    month.lower(): number
    for number, month in enumerate(calendar.month_name)
    if month
}

def get_bulletin_date(pdf_path):
    """
    Get the bulletin month and year from the PDF filename.

    Example:
    october_2016.pdf -> 2016-10-31

    The bulletin date is stored as the last day of the month because
    later calculations will compare cutoff dates with bulletin dates.
    """
    # Remove .pdf and split the filename into month and year.
    month_name, year = pdf_path.stem.rsplit("_", 1)

    # Convert the month name into its numerical value.
    month_number = MONTHS[month_name.lower()]

    # First, create the first day of that bulletin month.
    date = pd.Timestamp(
        year=int(year),
        month=month_number,
        day=1
    )

    # Convert it to the final day of the bulletin month.
    return date + pd.offsets.MonthEnd(0)

In [27]:
#test
get_bulletin_date(
    RAW_DIR / "2016" / "october_2016.pdf"
)

Timestamp('2016-10-31 00:00:00')

In [ ]:
def normalize_cutoff_value(value):
    """
    Clean cutoff values extracted from PDFs.

    In a few PDFs, pdfplumber reads the number 0 as the letter O.
    Example:
    O8NOV07 -> 08NOV07

    Only positions that should contain numbers are corrected.
    The month letters are left unchanged.
    """
    value = value.strip().upper()

    # Current and Unavailable do not need any cleaning. For now
    if value in {"C", "U"}:
        return value

    # Normal cutoff dates use the DDMMMYY format (7 characters).
    if len(value) == 7:
        chars = list(value)

        # Positions 0, 1, 5, and 6 should always contain numbers.
        for i in [0, 1, 5, 6]:
            if chars[i] == "O":
                chars[i] = "0"

        value = "".join(chars)

    return value

## Parser A: October 2016 – October 2025

The older PDFs do not behave like real PDF tables when using `extract_tables()`.

However, `pdfplumber` can extract the text correctly, so this parser:

1. Reads the PDF as text
2. Separates Final Action Dates and Dates for Filing
3. Finds rows for F1, F2A, F2B, F3, and F4
4. Cleans the cutoff values
5. Converts each table row into five dataset records

In [38]:
def parse_old_format(pdf_path):
    """
    Parse one old-format Visa Bulletin PDF.

    Expected output:
    50 records per bulletin

    5 visa categories
    x 5 chargeability areas
    x 2 table types
    = 50 records
    """

    # Extract all text from all pages of the PDF.
    with pdfplumber.open(pdf_path) as pdf:
        text = "\n".join(
            page.extract_text() or ""
            for page in pdf.pages
        )

    # Uppercase copy is used only for finding section headings consistently.
    upper_text = text.upper()

    # Find where the Final Action section begins.
    final_start = upper_text.find(
        "FINAL ACTION DATES FOR FAMILY-SPONSORED"
    )

    # Find where the Dates for Filing section begins.
    filing_start = upper_text.find(
        "DATES FOR FILING FAMILY-SPONSORED"
    )

    # If either section cannot be found, return no records.
    if final_start == -1 or filing_start == -1:
        return []

    # Separate the two family-sponsored tables.
    final_section = text[final_start:filing_start]
    filing_section = text[filing_start:]

    # Get the bulletin month from the filename.
    bulletin_date = get_bulletin_date(pdf_path)

    records = []

    # Process both Family-Sponsored tables separately.
    for table_type, section in [
        ("Final Action", final_section),
        ("Dates for Filing", filing_section)
    ]:
        # Read the section one line at a time.
        for line in section.splitlines():
            parts = line.strip().split()

            # A valid table row should contain:
            # 1 visa category + 5 cutoff values = 6 pieces.
            if len(parts) == 6 and parts[0] in { 
                "F1", "F2A", "F2B", "F3", "F4"
            }:
                category = parts[0]

                # Clean any PDF extraction errors in the cutoff values.
                values = [
                    normalize_cutoff_value(value)
                    for value in parts[1:]
                ]

                # Only accept the row if all five values are valid.
                if all(DATE_PATTERN.match(value) for value in values):

                    # Convert one table row into five records,
                    # one record for each chargeability area.
                    for area, value in zip(AREAS, values):
                        records.append({
                            "bulletin_date": bulletin_date,
                            "visa_category": category,
                            "chargeability_area": area,
                            "table_type": table_type,
                            "raw_cutoff_value": value
                        })

    return records

In [ ]:
# Test the old-format parser using the first bulletin in the dataset.
test_records = parse_old_format(
    RAW_DIR / "2016" / "october_2016.pdf"
)

# Each bulletin should produce 50 records:
# 5 visa categories × 5 chargeability areas × 2 table types.
print("Records:", len(test_records))

# Display the extracted records to visually confirm the parser output.
pd.DataFrame(test_records).head(50)

Records: 50

,bulletin_date,visa_category,chargeability_area,table_type,raw_cutoff_value
0,2016-10-31,F1,All Chargeability Areas Except Those Listed,Final Action,22SEP09
1,2016-10-31,F1,China,Final Action,22SEP09
2,2016-10-31,F1,India,Final Action,22SEP09
3,2016-10-31,F1,Mexico,Final Action,01APR95
4,2016-10-31,F1,Philippines,Final Action,01AUG05
5,2016-10-31,F2A,All Chargeability Areas Except Those Listed,Final Action,22DEC14
6,2016-10-31,F2A,China,Final Action,22DEC14
7,2016-10-31,F2A,India,Final Action,22DEC14
8,2016-10-31,F2A,Mexico,Final Action,01DEC14
9,2016-10-31,F2A,Philippines,Final Action,22DEC14
10,2016-10-31,F2B,All Chargeability Areas Except Those Listed,Final Action,15MAR10
11,2016-10-31,F2B,China,Final Action,15MAR10
12,2016-10-31,F2B,India,Final Action,15MAR10
13,2016-10-31,F2B,Mexico,Final Action,01OCT95
14,2016-10-31,F2B,Philippines,Final Action,01JAN06
15,2016-10-31,F3,All Chargeability Areas Except Those Listed,Final Action,22DEC04
16,2016-10-31,F3,China,Final Action,22DEC04
17,2016-10-31,F3,India,Final Action,22DEC04
18,2016-10-31,F3,Mexico,Final Action,22NOV94
19,2016-10-31,F3,Philippines,Final Action,08JUL94
20,2016-10-31,F4,All Chargeability Areas Except Those Listed,Final Action,01NOV03
21,2016-10-31,F4,China,Final Action,01MAY03
22,2016-10-31,F4,India,Final Action,01DEC02
23,2016-10-31,F4,Mexico,Final Action,01MAY97
24,2016-10-31,F4,Philippines,Final Action,15APR93
25,2016-10-31,F1,All Chargeability Areas Except Those Listed,Dates for Filing,01JAN11
26,2016-10-31,F1,China,Dates for Filing,01JAN11
27,2016-10-31,F1,India,Dates for Filing,01JAN11
28,2016-10-31,F1,Mexico,Dates for Filing,01JUN95
29,2016-10-31,F1,Philippines,Dates for Filing,01MAY06
30,2016-10-31,F2A,All Chargeability Areas Except Those Listed,Dates for Filing,22NOV15
31,2016-10-31,F2A,China,Dates for Filing,22NOV15
32,2016-10-31,F2A,India,Dates for Filing,22NOV15
33,2016-10-31,F2A,Mexico,Dates for Filing,22NOV15
34,2016-10-31,F2A,Philippines,Dates for Filing,22NOV15
35,2016-10-31,F2B,All Chargeability Areas Except Those Listed,Dates for Filing,08FEB11
36,2016-10-31,F2B,China,Dates for Filing,08FEB11
37,2016-10-31,F2B,India,Dates for Filing,08FEB11
38,2016-10-31,F2B,Mexico,Dates for Filing,01JUN96
39,2016-10-31,F2B,Philippines,Dates for Filing,01FEB07
40,2016-10-31,F3,All Chargeability Areas Except Those Listed,Dates for Filing,22AUG05
41,2016-10-31,F3,China,Dates for Filing,22AUG05
42,2016-10-31,F3,India,Dates for Filing,22AUG05
43,2016-10-31,F3,Mexico,Dates for Filing,01MAY95
44,2016-10-31,F3,Philippines,Dates for Filing,01JAN95
45,2016-10-31,F4,All Chargeability Areas Except Those Listed,Dates for Filing,01JUL04
46,2016-10-31,F4,China,Dates for Filing,01JUL04
47,2016-10-31,F4,India,Dates for Filing,01MAY04
48,2016-10-31,F4,Mexico,Dates for Filing,01DEC97
49,2016-10-31,F4,Philippines,Dates for Filing,01APR94

In [ ]:
# Collect all PDFs that use the old bulletin format.
# The old format covers October 2016 through October 2025.
old_format_files = []

# Search through all PDF files in the raw data folder.
for pdf_path in sorted(RAW_DIR.rglob("*.pdf")):
    bulletin_date = get_bulletin_date(pdf_path)

    # Keep only bulletins dated October 2025 or earlier!!!
    if bulletin_date <= pd.Timestamp("2025-10-31"):
        old_format_files.append(pdf_path)

# Confirm how many PDFs belong to the old format. Expected: 109
print("Old-format PDF count:", len(old_format_files))

Old-format PDF count: 109

In [ ]:
# Store all extracted records from the old-format PDFs.
all_old_records = []
# Store the record count for each PDF so the parsing can be validated later.
validation_results = []

# Parse every old-format Visa Bulletin PDF.
for pdf_path in old_format_files:
    records = parse_old_format(pdf_path)

    # Save the number of records extracted from each PDF.
    # Each bulletin should produce exactly 50 records.
    validation_results.append({
        "file": pdf_path.name,
        "records": len(records)
    })

    # Add the records from this bulletin to the full old-format dataset.
    all_old_records.extend(records)

# Confirm the total number of extracted records.
# 109 bulletins × 50 records = 5,450 expected records.
print("Total records from all old-format PDFs:", len(all_old_records))

# Preview the validation results for the first 50 PDFs
print(pd.DataFrame(validation_results).head(50))

Total records from all old-format PDFs: 5450
                  file  records
0    december_2016.pdf       50
1    november_2016.pdf       50
2     october_2016.pdf       50
3       april_2017.pdf       50
4      august_2017.pdf       50
5    december_2017.pdf       50
6    february_2017.pdf       50
7     january_2017.pdf       50
8        july_2017.pdf       50
9        june_2017.pdf       50
10      march_2017.pdf       50
11        may_2017.pdf       50
12   november_2017.pdf       50
13    october_2017.pdf       50
14  september_2017.pdf       50
15      april_2018.pdf       50
16     august_2018.pdf       50
17   december_2018.pdf       50
18   february_2018.pdf       50
19    january_2018.pdf       50
20       july_2018.pdf       50
21       june_2018.pdf       50
22      march_2018.pdf       50
23        may_2018.pdf       50
24   november_2018.pdf       50
25    october_2018.pdf       50
26  september_2018.pdf       50
27      april_2019.pdf       50
28     august_2019.pdf       50
29   december_2019.pdf       50
30   february_2019.pdf       50
31    january_2019.pdf       50
32       july_2019.pdf       50
33       june_2019.pdf       50
34      march_2019.pdf       50
35        may_2019.pdf       50
36   november_2019.pdf       50
37    october_2019.pdf       50
38  september_2019.pdf       50
39      april_2020.pdf       50
40     august_2020.pdf       50
41   december_2020.pdf       50
42   february_2020.pdf       50
43    january_2020.pdf       50
44       july_2020.pdf       50
45       june_2020.pdf       50
46      march_2020.pdf       50
47        may_2020.pdf       50
48   november_2020.pdf       50
49    october_2020.pdf       50

In [50]:
# Convert the validation results into a DataFrame.
validation_df = pd.DataFrame(validation_results)

# Show only bulletins that did NOT produce the expected 50 records.
# An empty result means every old-format PDF passed validation.
validation_df[validation_df["records"] != 50]

Empty DataFrame
Columns: [file, records]
Index: []

In [51]:
# Convert all successfully parsed old-format records into a DataFrame.
old_df = pd.DataFrame(all_old_records)

# Confirm the expected dataset size:
# 109 bulletins × 50 records = 5,450 rows.
print("Old-format dataset shape:", old_df.shape)

# Preview the dataset.
old_df.head()

Old-format dataset shape: (5450, 5)

,bulletin_date,visa_category,chargeability_area,table_type,raw_cutoff_value
0,2016-12-31,F1,All Chargeability Areas Except Those Listed,Final Action,01DEC09
1,2016-12-31,F1,China,Final Action,01DEC09
2,2016-12-31,F1,India,Final Action,01DEC09
3,2016-12-31,F1,Mexico,Final Action,15APR95
4,2016-12-31,F1,Philippines,Final Action,15SEP05

## Parser B: November 2025 – September 2026

The newer Visa Bulletin PDFs contain tables that `pdfplumber` can detect directly using `extract_tables()`.

This parser will extract the same 50 records per bulletin as Parser A, but using the PDF table structure instead of text-based parsing.

In [53]:
# Collect PDFs that use the new bulletin format.
# The new format begins in November 2025 and continues through September 2026.
new_format_files = []

# Search all downloaded PDFs and select only the new-format period.
for pdf_path in RAW_DIR.rglob("*.pdf"):
    bulletin_date = get_bulletin_date(pdf_path)

    if bulletin_date >= pd.Timestamp("2025-11-30"):
        new_format_files.append(pdf_path)

# November 2025 through September 2026 should contain 11 bulletins.
print("New-format PDF count:", len(new_format_files))

New-format PDF count: 11

In [54]:
def parse_new_format(pdf_path):
    """
    Parse one new-format Visa Bulletin PDF.

    New-format PDFs contain detectable table structures, so this parser
    uses pdfplumber's extract_tables() instead of text-based parsing.

    Expected output:
    50 records per bulletin

    5 visa categories
    × 5 chargeability areas
    × 2 table types
    = 50 records
    """

    # Get the bulletin date from the PDF filename.
    bulletin_date = get_bulletin_date(pdf_path)

    # This list will store the two Family-Sponsored tables:
    # Final Action Dates and Dates for Filing.
    family_tables = []

    # Open the PDF and check every page for tables.
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:

            # Extract all detectable tables from the current page.
            tables = page.extract_tables()

            for table in tables:
                family_rows = []

                # Check each row inside the extracted table.
                for row in table:
                    if not row:
                        continue

                    # Replace empty cells with "" and remove extra spaces.
                    cells = [
                        (cell or "").strip()
                        for cell in row
                    ]

                    # A Family-Sponsored data row should contain:
                    # category + 5 chargeability-area values.
                    if (
                        len(cells) == 6
                        and cells[0] in {"F1", "F2A", "F2B", "F3", "F4"}
                    ):
                        family_rows.append(cells)

                # A complete Family-Sponsored table should contain
                # exactly the five categories.
                if len(family_rows) == 5:
                    family_tables.append(family_rows)

    # We expect exactly two Family-Sponsored tables in each bulletin.
    if len(family_tables) != 2:
        return []

    records = []

    # The tables appear in this order in the bulletin:
    # 1. Final Action Dates
    # 2. Dates for Filing
    for table_type, table in zip(
        ["Final Action", "Dates for Filing"],
        family_tables
    ):

        for row in table:
            category = row[0]

            # Clean possible PDF extraction errors in cutoff values.
            values = [
                normalize_cutoff_value(value)
                for value in row[1:]
            ]

            # Only use the row if all five cutoff values are valid.
            if all(DATE_PATTERN.match(value) for value in values):

                # Convert one table row into five records,
                # one for each chargeability area.
                for area, value in zip(AREAS, values):
                    records.append({
                        "bulletin_date": bulletin_date,
                        "visa_category": category,
                        "chargeability_area": area,
                        "table_type": table_type,
                        "raw_cutoff_value": value
                    })

    return records

In [55]:
# Test Parser B using the first new-format bulletin.
test_new_records = parse_new_format(
    RAW_DIR / "2025" / "november_2025.pdf"
)

# A successful bulletin should produce 50 records.
print("Records:", len(test_new_records))

# Preview the first few extracted records.
pd.DataFrame(test_new_records).head()

Records: 50

,bulletin_date,visa_category,chargeability_area,table_type,raw_cutoff_value
0,2025-11-30,F1,All Chargeability Areas Except Those Listed,Final Action,08NOV16
1,2025-11-30,F1,China,Final Action,08NOV16
2,2025-11-30,F1,India,Final Action,08NOV16
3,2025-11-30,F1,Mexico,Final Action,22NOV05
4,2025-11-30,F1,Philippines,Final Action,22JAN13

In [56]:
# Store all extracted records from the new-format PDFs.
all_new_records = []

# Store the record count for each PDF so the parsing can be validated.
new_validation_results = []

# Parse every new-format Visa Bulletin PDF.
for pdf_path in new_format_files:
    records = parse_new_format(pdf_path)

    # Each bulletin should produce exactly 50 records.
    new_validation_results.append({
        "file": pdf_path.name,
        "records": len(records)
    })

    # Add the records from this bulletin to the full new-format dataset.
    all_new_records.extend(records)

# Confirm the expected total:
# 11 bulletins × 50 records = 550 records.
print("Total records from all new-format PDFs:", len(all_new_records))

Total records from all new-format PDFs: 550

In [57]:
# Convert the validation results into a DataFrame.
new_validation_df = pd.DataFrame(new_validation_results)

# Show only bulletins that did NOT produce the expected 50 records.
# An empty result means every new-format PDF passed validation.
new_validation_df[new_validation_df["records"] != 50]

Empty DataFrame
Columns: [file, records]
Index: []

In [58]:
# Convert all successfully parsed new-format records into a DataFrame.
new_df = pd.DataFrame(all_new_records)

# Confirm the expected dataset size.
print("New-format dataset shape:", new_df.shape)

# Preview the first few rows.
new_df.head()

New-format dataset shape: (550, 5)

,bulletin_date,visa_category,chargeability_area,table_type,raw_cutoff_value
0,2025-11-30,F1,All Chargeability Areas Except Those Listed,Final Action,08NOV16
1,2025-11-30,F1,China,Final Action,08NOV16
2,2025-11-30,F1,India,Final Action,08NOV16
3,2025-11-30,F1,Mexico,Final Action,22NOV05
4,2025-11-30,F1,Philippines,Final Action,22JAN13

In [59]:
# Combine the old-format and new-format datasets.
full_df = pd.concat(
    [old_df, new_df],
    ignore_index=True
)

# Sort the dataset chronologically.
full_df = full_df.sort_values(
    by=[
        "bulletin_date",
        "table_type",
        "visa_category",
        "chargeability_area"
    ]
).reset_index(drop=True)

# Confirm the expected dataset size:
# 120 bulletins × 50 records = 6,000 rows.
print("Full dataset shape:", full_df.shape)

# Preview the first few rows.
full_df.head()

Full dataset shape: (6000, 5)

,bulletin_date,visa_category,chargeability_area,table_type,raw_cutoff_value
0,2016-10-31,F1,All Chargeability Areas Except Those Listed,Dates for Filing,01JAN11
1,2016-10-31,F1,China,Dates for Filing,01JAN11
2,2016-10-31,F1,India,Dates for Filing,01JAN11
3,2016-10-31,F1,Mexico,Dates for Filing,01JUN95
4,2016-10-31,F1,Philippines,Dates for Filing,01MAY06

In [ ]:
# Confirm that the dataset contains all 120 monthly bulletins.
print(
    "Unique bulletin months:",
    full_df["bulletin_date"].nunique()
)

# Check how many records exist for each bulletin.
records_per_bulletin = (
    full_df
    .groupby("bulletin_date")
    .size()
)

print(records_per_bulletin)

# Show any bulletin that does NOT contain exactly 50 records.
records_per_bulletin[records_per_bulletin != 50]

Unique bulletin months: 120
bulletin_date
2016-10-31    50
2016-11-30    50
2016-12-31    50
2017-01-31    50
2017-02-28    50
              ..
2026-05-31    50
2026-06-30    50
2026-07-31    50
2026-08-31    50
2026-09-30    50
Length: 120, dtype: int64

Series([], dtype: int64)

In [61]:
# Each combination of bulletin, category, area, and table type
# should appear only once.
duplicate_rows = full_df.duplicated(
    subset=[
        "bulletin_date",
        "visa_category",
        "chargeability_area",
        "table_type"
    ]
).sum()

print("Duplicate records:", duplicate_rows)

Duplicate records: 0

In [63]:
# Check the unique cutoff values that are not standard dates, C, or U.
unexpected_values = full_df[
    ~full_df["raw_cutoff_value"].str.match(
        r"^(?:\d{2}[A-Z]{3}\d{2}|C|U)$"
    )
]

print("Unexpected cutoff values:", len(unexpected_values))

Unexpected cutoff values: 0

In [64]:
# Save the structured dataset created directly from the PDF files.
output_path = PROCESSED_DIR / "visa_bulletins_6000_raw.csv"

full_df.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("Final shape:", full_df.shape)

Saved to: /Users/serratak/Desktop/visa-bulletin-project/visa-bulletin-project/data/processed/visa_bulletins_6000_raw.csv
Final shape: (6000, 5)

In [65]:
print("File exists:", output_path.exists())

File exists: True